### ISSUE TITLE
1-1 enabled with AHKCSortie

### ISSUE THREAD

**Issue by mintgreenrose** [Ryuuhou/AHKanColle#11]
Is there any way 1-1 can be included in the supported maps AHKCSortie supports? It would be incredibly useful for sparkling lots of ships without the tediousness

**Comment by Ryuuhou** [comment]
You may test it here. Change nodes to 2 so it continues past the first node.  Nodes will not be saved in config.ini due to concerns of sinking.

EDIT: Committed to master branch, you may now update from the main page.

**Comment by mintgreenrose** [comment]
Heeey man thanks! Don't think that lil abyssal DD at first node can taiha anything above Level 10 though, but thanks for the concern, for listening to suggestions and for always keepin this lil gem updated

**Comment by Ryuuhou** [comment]
No problem, closing issue
