### ISSUE TITLE
Stuck on "Waiting for home screen"

### ISSUE THREAD

**Issue by ronelm2000** [Ryuuhou/AHKanColle#15]
OS: Windows 10

Using both KC3 Kai - Google Chrome and (insert official website title) - Google Chrome as WINID. Either configuration doesn't work.

First Exped has remaining time.

When I simply press "ENTER", it says "Manual send in 0.00 seconds" then it doesn't auto-resend expeds.

Or it goes to the wallpaper, says "Waiting for home screen..." forever.

Config.ini is as follows:
[Variables]
WINID=艦隊これくしょん -艦これ- - オンラインゲーム - DMM.com - Google Chrome (when using KC3 Kai this is different)
Background=1
//Script attempts to click without losing focus from other windows. When set to 0, clicks are no longer done in background.  May fix issues with certain viewers.
Class=0
//When set to class name, i.e. Internet Explorer_Server1, the script will click directly on the class rather than the window.  May fix issues with certain applications. This setting is ignored if Background=0
DisableCriticalCheck=0
LastX=1031
LastY=493
SetExped4=21
SetExped3=6
SetExped2=2
LastXS=0
LastYS=0
MaxRandomWait=2000
MinRandomWait=1000

PS: KCV works, it's just that I want to use this with KC3 Kai, which has in-battle HP viewer. And isn't Yuubari's KCV which puts some things in rather wierd perspectives (like the ship overview being too ... whatever)

**Comment by Ryuuhou** [comment]
You're right, I'm trying to figure out why.

**Comment by Ryuuhou** [comment]
Nvm, it's because of Chrome hardware acceleration, turn it off in Chrome's advanced settings.  Also note that Chrome does not like to be clicked in background so the window will pop up every time script runs. (It won't move your mouse, but it will pop up) Let me know if this solves your issue.

**Comment by ronelm2000** [comment]
Hmm, it does fix the issue (better add that in Chrome, since I really did not know she used Hardware Accel and it was turned on), but, you did say:

Do NOT use hardware acceleration on your browsers or use "Direct/GPU" on KCV unless your computer is set to never idle. When the computer idles, hardware acceleration is turned off and flash no longer renders.

When I never set the computer on Idle (which I don't), so I thought it's supposed to be a non-issue. But I guess it does (for one it doesn't run, at all.)

**Comment by Ryuuhou** [comment]
Yeah, I dunno. I tested a long time ago and the script still ran on Chrome with hardware accel, only issue was when the PC went to idle.  Chrome may have changed how hardware accel works now, I will update the readme.
