### ISSUE TITLE
Pause Utility issue

### ISSUE THREAD

**Issue by Runarisu** [Ryuuhou/AHKanColle#19]
Can't seem to get the Pause utility to work properly, doesn't activate despite following the instructions on the main page, checked script and my config and noticed this, I've included the image to help.

https://puu.sh/qyNzl/c4b0ac5bee.png

just wondering if I've set it up incorrectly or I've done something wrong @Ryuuhou

rest of the code looks fine but the -1 is a bit offputting. However if the rest of the script needs to be examined then I can share it if required. The Pause Utility is successfully displaying on start up "script will be paused at this time and resumed at this time" however its not actually pausing or resuming anything. Because if I'm reading the script properly, it should notify you if the pause was successful?

**Comment by Ryuuhou** [comment]
I have confirmed that this is currently not working, will investigate more soon.

**Comment by Ryuuhou** [comment]
Should be fixed in this commit https://github.com/Ryuuhou/AHKanColle/commit/b3c6027b245f23cbb39c9ab5aa71d9958e2ec9a9

Release: https://github.com/Ryuuhou/AHKanColle/releases
Please let me know if this solves your issue, closing issue in a few days.

**Comment by Runarisu** [comment]
haven't been able to test it because my game is catbombing itself whenever it wants now, but I'm going to assume the error has been fixed since on initial view it looks like its pulling the correct details now.

Wouldn't mind an auto refresh on catbomb + pressing of the game start button so it can pick up from where it left off, but this maybe too "automatic" (and also would possibly only function on KCV, at that)

**Comment by Ryuuhou** [comment]
Auto refresh on catbomb is planned, don't know when I'll get time to implement it.
