### ISSUE TITLE
[Help] An expedition is returning, retrying every 10 seconds

### ISSUE THREAD

**Issue by dice4321** [Ryuuhou/AHKanColle#20]
ello, I got it to work for google chrome KC3 but I get this error, even tried it on KCV, even tho I have no expeditions running at all.

http://i.imgur.com/qKsBYQE.jpg

**Comment by Ryuuhou** [comment]
Do you have AHKanColle running too?

**Comment by dice4321** [comment]
@Ryuuhou nope, only AHKCSortie

**Comment by Ryuuhou** [comment]
You need to run both even if you aren't sending expeditions.  Set Remaining Time to -1 and it'll run.  I'll update the README to make this clearer.

**Comment by dice4321** [comment]
@Ryuuhou I switched over to KCV and wow works like a charm for sparkling! Thank you! Then switched back to KC3 to see what was up.

I ran into the same problem as ronelm2000 with the "Stuck on "Waiting for home screen", didn't know that was the hardware acceleration problem until I read that thread, heh. Thanks again for the help!
