### ISSUE TITLE
[Feature request] Skip repair

### ISSUE THREAD

**Issue by dice4321** [Ryuuhou/AHKanColle#21]
Your project works great! But when I'm sparkling, the script would repair the lvl 1 ships I'm using as fodder, is it possible to add a config option to skip repairs? Maybe even pause the script when a ship needs repairs?

**Comment by Ryuuhou** [comment]
https://github.com/Ryuuhou/AHKanColle/releases/tag/v1.60814a
I cannot differentiate from the first ship being red to random fodder ship so I cannot pause it when the main ship is red.

**Comment by dice4321** [comment]
@Ryuuhou this is perfect, thank you, thank you, thank you!
