### ISSUE TITLE
Miss-clickin' into PVP

### ISSUE THREAD

**Issue by burstlimit95** [Ryuuhou/AHKanColle#22]
Oy,

So far AHKancolle has worked pretty well for me. But right now, i can't get expedition 21 laucnhed.

I'm using KC3 under Chrome, used the Spy tool, the config.ini is alright, and the script worked fine until i decided to launch E21. When i launch the script for E21, it checks ammo, get back to main menu, get to expedition menu, it selects world 3 and then, intead of selecting E21 as requested, the scipt clicks PVP :v: 

I've tried to change the window ID in the config.ini, tried to launch it with a full-sized game and non full'sized game. Can't make ir work.  My screen is 1366x768, i don't think that'd be the issue since every other expeditions worked so far. 

Excuse my bad eng' :v

**Comment by Ryuuhou** [comment]
Do you have all the expeditions unlocked?  Your world 3 expedition page should look like this http://puu.sh/qCPeJ/7bd0c8cb88.jpg

If you do not have them all unlocked, you can edit the source code.  Determine which expedition is supposed to be where your expedition 21 is using my image.  Example: If your expedition list is 17,18,19,21 then you are missing expedition 20 and expedition 21 is currently in the spot where expedition 20 should be.  In the folder "Constants," edit "ExpeditionTime.ahk and change ET[20] to the time of ET[21].  So it would look like ET[20]=8400000.  Now run the script and run expedition 20, it will run expedition 21.

**Comment by burstlimit95** [comment]
All right, i see what's the problem here then. I didn't think of it but now you say it, it seems obvious.
I have indeed not unlocked every Exp for W3, i'll unlock them all and see if the problem  is resolved, thanks for the quick answer :^)

**Comment by burstlimit95** [comment]
Hi there,

Well, finished unlocking everything, and it works perfectly!

**Comment by Ryuuhou** [comment]
Glad it works, thanks for the update.
