### ISSUE TITLE
How do you get the x,y pixels on kancolle viewer?

### ISSUE THREAD

**Issue by dice4321** [Ryuuhou/AHKanColle#28]
Im trying to make some anti detection features, where instead of clicking directly to go to supply, it would go through a few random screens first, I've tried the AHK pixel detection thing, it just doesnt make any sense with the pixel map @Ryuuhou pls!

**Comment by Ryuuhou** [comment]
Hey, sorry for the late response. I've been busy this week. I wrote a new tool called XYColor.  You can find it on the master branch here https://github.com/Ryuuhou/AHKanColle/commit/6244a5b26cd603ab9701be94ff9dcf8efc0e9e7a
Just open the AHK file and right click the game where you want to find the X,Y and pixel color at that position.  Remember that you will always be in reference to FX and FY, so if XYColor says FX +50 and FY -20, you need to write that in the code.  FX+50 and FY-20.

**Comment by dice4321** [comment]
@Ryuuhou thanks mate, I'll make you proud.
