### ISSUE TITLE
not sending fleet 3 and 4 to expedition

### ISSUE THREAD

**Issue by blacksworfsman** [Ryuuhou/AHKanColle#35]
it can send fleet 2 to exped no problem but when it needs to choose the fleet to send when trying to send fleet 3 and 4, it gets stuck on fleet 2.

using KC3 Kai as my viewer

**Comment by dice4321** [comment]
yep, turns out raising the random pixel to 7 would avoid the catbomb but mess a few things up, to fix this go into your `pixelmap.ahk` in functions and change the expedition pixel to these values:

	ESx := FX + 290

	ESy := FY - 11

	3Ex := FX + 47

	4Ex := FX + 78

	34Ey := FY - 344

**Comment by Ryuuhou** [comment]
thanks diceman112, closed.
https://github.com/Ryuuhou/AHKanColle/releases/tag/v1.70516
