### ISSUE TITLE
AHKancolle And AHKSortie Is Not Clicking The Start When Sortie/Expedition

### ISSUE THREAD

**Issue by Cristonz** [Ryuuhou/AHKanColle#36]
Thanks For Your Great Work There, But I Have a Problem Here, Game Stuck Here But AHKSortie Showing Waiting Compass/Formation,
Tried On Chrome/FireFox/IE, It Also Happen In AHKancolle, Please Help.

![capture](https://cloud.githubusercontent.com/assets/28746634/26138321/f2b34dfc-3afa-11e7-9300-c46103ad3467.JPG)

**Comment by Ryuuhou** [comment]
Should be fixed now. https://github.com/Ryuuhou/AHKanColle/commit/272b42f5d71942aaabbda3fb3ba53420037e8806
https://github.com/Ryuuhou/AHKanColle/releases/tag/v1.70516

**Comment by Cristonz** [comment]
Is Working Fine Now, Thank You So Much For Your Help ~
