### ISSUE TITLE
How do I use an array in ahk

### ISSUE THREAD

**Issue by dice4321** [Ryuuhou/AHKanColle#37]
This is the test code I'm using

```

	loop, 6
	{
		GuiControl,, NB, Checking HP %A_Index%
		tpc := PixelGetColorS(ShipHealthx,ShipHealthy%A_Index%,3)
		GuiControl,, NB, Color is %tpc%
		sleep 1000
		if (tpc5 = RedHealthPC)
		{
			GuiControl,, NB, RED detected
			if (world !=1 and map != 1)
			{
				NC := Nodes
			}
		}
	}

```

I've initialized the array 

```
Initialize()
{
    global
	SPGx := Array(item)
	MAPx := Array(item)
	MAPy := Array(item)
	ShipHealthy := Array(item)
	pc := Array(item)
  	Q := Array()
	NC := 0
	ClickDelay := 50
	coffset := 7
}
```

and array inputs in the pixelmap.ahk file

```
ShipHealthx := FX - 52
ShipHealthy[1] := FY - 238
ShipHealthy[2] := FY - 193
ShipHealthy[3] := FY - 148
ShipHealthy[4] := FY - 103
ShipHealthy[5] := FY - 58
ShipHealthy[6] := FY - 13

```
Testing on the home screen of kancolle, its suppose to give you a different color every check since its checking pixels vertically but, it shows up the same color every check. What am I doing wrong?
![upload 337](https://cloud.githubusercontent.com/assets/20022859/26674708/24652f06-4676-11e7-970c-a9c98384cb34.png)

**Comment by Ryuuhou** [comment]
hmm.. does it say "Checking HP 1 to 6"? I do not see the problem right now, try using a msgbox within the loop to show the value of ShipHealthy%A_Index%.

**Comment by dice4321** [comment]
Ah, thank you, your suggestion was extremely helpful!

When I tried to get ShipHealthy%A_Index%. to show in the message box nothing would come up, so instead, I tried 		

```
	loop, 6
	{
		GuiControl,, NB, Checking HP %A_Index%
		tpc := PixelGetColorS(ShipHealthx,ShipHealthy[A_Index],3)
		tempx := ShipHealthy[A_Index]
		GuiControl,, NB, Color is %tempx%
```

 and it worked....well at least im getting different numbers heh.
