### ISSUE TITLE
Invalid screen (retrying)

### ISSUE THREAD

**Issue by dice4321** [Ryuuhou/AHKanColle#38]
on the 10/25 update, it seems they changed the color of the start screen just very so slightly and now the pixel search wont even recognize the start screen. From what I'm reading from the pixel search function, it seaches for a specific color on the bucket and sets the x and y axis for the entire pixel map after that

![image](https://user-images.githubusercontent.com/20022859/31994342-2b3cc4ec-b935-11e7-8ed0-6dfd63a45c38.png)

Since the colors have changed, I have no idea where the x and y axis of those buckets colors are, and since the whole entire program relys on the bucket color, I cannot even start updating for these new colors. Ryuuhou,  SOS. 

As you can see here, the slight changes 

https://cdn.discordapp.com/attachments/298881300402536460/372697749608595458/DM-aak8XUAE81fI.png

https://cdn.discordapp.com/attachments/298881300402536460/372697775827058698/DM-acswWsAAPoul.png

**Comment by Ryuuhou** [comment]
Missed your message, you are correct about how it worked. Two things changed that made this update particularly challenging. The bucket and the blue notification circle at the bottom middle which is mapped to FX,FY.  I have chosen a different reference pixel at the very top of the game border where this is one odd pinkish color as it transitions to black. Hopefully that will remain for a while. 

here is a pre-release https://github.com/Ryuuhou/AHKanColle/releases/tag/v1.71214

Only expeditions are working at the moment.

**Comment by dice4321** [comment]
Excellent patch, thank you Ryuuhou, the script is once again responsive! There is one more problems that I've encountered when I referred this program to a friend of mine, if the player changes the floor of the admiral room, or choose a secretary with a model larger enough to come into contact with the background of the FX,FY coordinates, the pixel color changes ever so slightly so that the script no longer recognizes the pixel color referred to as HPC := 0x33b3b4 or HEPC as seen here.


![image](https://user-images.githubusercontent.com/20022859/34037294-21f93b38-e13d-11e7-9ac7-cb41607de7ac.png)



Is there a way to make the pixel search recognize shades of a color?

**Comment by Ryuuhou** [comment]
As far as I know, no I cannot make the GetPixelColor take a shade but I can find another reference point that isnt FX,FY that doesn't change colors with background changes. Possibly the lower border? Thanks for the bug report. Until I fix that, you can advise your friend to change the HPC constant to the color matching his background.

**Comment by Ryuuhou** [comment]
Fixed in: https://github.com/Ryuuhou/AHKanColle/commit/aa4fb0f53d949595748fde42a962db2d940b7c57
Pre-release: https://github.com/Ryuuhou/AHKanColle/releases

The home check now uses the settings gear rather than the notification button. The settings gear did not change color for me so this should be a better detection method.

**Comment by dice4321** [comment]
Wonderful,wonderful! With this, all known bugs are fixed, you have my gratitude!
