### ISSUE TITLE
Does not resupply properly

### ISSUE THREAD

**Issue by jun154** [Ryuuhou/AHKanColle#4]
Doesnt resupply properly since now you only have to click the select all ships in the fleet to resupply it. Currently it goes into the resupply page and does not resupply anything and gets sent into the expedition, causing the expedition to fail.

**Comment by Ryuuhou** [comment]
I updated the script before I responded to you, it still happens?

**Comment by Ryuuhou** [comment]
https://github.com/Ryuuhou/AHKanColle/releases

**Comment by jun154** [comment]
It still breaks at the resupply part.

**Comment by Ryuuhou** [comment]
I am not sure, it works fine on my end.  Can you double check that your AHKanColle.ahk has these changes? https://github.com/Ryuuhou/AHKanColle/commit/ebf0df984b62599f9da06a671c4d31593d1ad1ae

**Comment by jun154** [comment]
Yes it has these changes

**Comment by Ryuuhou** [comment]
So I figured out that the new resupply mechanic is really weird and requires you to hover over it before it can be clicked.  I did a work around that will select the ships manually and ignores the button entirely.  Try it now.  (Its not a release, download the zip from the master)

**Comment by Ryuuhou** [comment]
https://github.com/Ryuuhou/AHKanColle/releases

**Comment by aruruuruuu** [comment]
when i thought its finally working, i got this bug too. when its time to resupply its clicking the home screen button(that make UI gone) not resuply menu

**Comment by Ryuuhou** [comment]
That's actually a different issue than the original poster. It may have to do with quality settings (script was made for High quality, Opaque setting, 800x640 resolution).  Does it happen every single time?  If it does, can you take a screenshot of your home screen and link it here?

**Comment by aruruuruuu** [comment]
but when i go to supply menu manually its working and automating the expedition, its error only when the expedition come back
![screenshot_5](https://cloud.githubusercontent.com/assets/13392388/10419552/0c2c3ae8-70b6-11e5-9c04-af0f2b49721f.jpg)

**Comment by Ryuuhou** [comment]
I wanted a screenshot of the home menu, let me know if it happens again when the expedition returns.

**Comment by aruruuruuu** [comment]
![screenshot_6](https://cloud.githubusercontent.com/assets/13392388/10419609/63f5e200-70b7-11e5-8849-358b591e8302.jpg)
how about this? if what u mean the game screen, its about 800x480 i think

**Comment by Ryuuhou** [comment]
Did you happen to be looking at your notifications? (The teal small button at the bottom), I use that button to detect home screen so try not to leave it expanded.

**Comment by aruruuruuu** [comment]
ah that arrow small button? well if u mean that button i never leave it expanded, always hidden

**Comment by Ryuuhou** [comment]
I am not entirely sure then, let me know if it happens the next time it comes back.

**Comment by aruruuruuu** [comment]
precisely i need to tell u when the first time i use the AHKancolle, all setting done and then i klik "send expedition" and its suddenly go to the disappear UI mode. that mean whenever the script supposedly go to supply menu its always go to no UI mode, all doing right exept that part

**Comment by Ryuuhou** [comment]
I think github compressed the image, can you printscreen, save it as png and upload to imgur?  I'm trying to find out why its not detecting the color.

**Comment by Ryuuhou** [comment]
I have just tested on KCKai and I didn't have any issues.  Make sure the flash is set to high quality, and do not scroll the game, the script assumes you don't move anything inside the window.

**Comment by jun154** [comment]
Thanks! Mine works now.

**Comment by Ryuuhou** [comment]
Since the actual original issue is solved, I'm closing this issue.  aruruuruuu, if you still have issues, feel free to open a new issue.
