### ISSUE TITLE
Windows not found

### ISSUE THREAD

**Issue by aruruuruuu** [Ryuuhou/AHKanColle#5]
where did i go wrong about this @Ryuuhou
![ahkancolle](https://cloud.githubusercontent.com/assets/13392388/10415414/06ff64be-7034-11e5-900e-7c16e51b7545.jpg)

**Comment by Ryuuhou** [comment]
How are you playing KanColle? Browser? KCV? Open the window spy that comes with autohotkey and click on your game. Copy the window title and add it to the config.ini. See the readme for formatting

**Comment by aruruuruuu** [comment]
thankyou very much!, its working now ^_^

**Comment by Ryuuhou** [comment]
You should update the script since I just fixed a resupply bug, but I'm glad you got it to work.
https://github.com/Ryuuhou/AHKanColle/releases
