### ISSUE TITLE
resupply

### ISSUE THREAD

**Issue by aruruuruuu** [Ryuuhou/AHKanColle#6]
@Ryuuhou heres the screen shot

http://i.imgur.com/ebUU5eR.jpg

http://i.imgur.com/biIlB8r.jpg

http://i.imgur.com/R4gFgRH.jpg

when the "1st" time its supposedly go to resupply,its clicking the home screen button instead, but if i go to resupply menu manually its going smoothly even after resupplying 1 fleet its go to the home and then go to resupply menu automaticly until all expedition fleet done and sent it automaticly to the expedition i desire

**Comment by Ryuuhou** [comment]
https://github.com/Ryuuhou/AHKanColle/blob/Debug/AHKanColle.ahk
Replace your AHKanColle with this one, it'll help me test what color its getting.  Use it on the main menu where you see your secretary (just send a 0 timer expedition).  A pop-up will appear, can you tell me what the pop up says?

**Comment by aruruuruuu** [comment]
http://i.imgur.com/oIY9sFf.jpg

that's what the pop up say

**Comment by Ryuuhou** [comment]
Thanks, that's a weird result. Let's do that again to narrow down the issue.  Use this branch, there should be 3 pop ups.  https://github.com/Ryuuhou/AHKanColle/tree/Debug?files=1

**Comment by aruruuruuu** [comment]
1st http://i.imgur.com/OpEeuMZ.jpg
2nd http://i.imgur.com/mCwlJgD.jpg
3rd http://i.imgur.com/Xx4sv5G.jpg
4th http://i.imgur.com/CmB8Muu.jpg

thats all

**Comment by Ryuuhou** [comment]
I'm trying to figure out the problem but I suspect it had to do with windows xp and the window being in the background. Can you go back to the original files of AHkanColle and add Background=0 into the config.ini under variables? Refer to the readme if you're confused on the format. Let me know if it works. I know this will physically move your mouse and take focus but I don't think background pixel checking works in windows xp.

**Comment by aruruuruuu** [comment]
still waiting for expedition to comeback. btw why its didnt work when after i manually go to resupply menu its working fine @_@

**Comment by aruruuruuu** [comment]
yeah its still clicking the homescreen button that make it to no UI mode

**Comment by Ryuuhou** [comment]
Are you sure you restarted the script after disabling background? Do you see your mouse moving?

**Comment by aruruuruuu** [comment]
1st i tried it at sortie menu. its clicking mainmenu button to go back to mainmenu, then clicking it again so its going to the no UI screen. 2nd i tried it at main menu, its clicking the mainmenu twice

**Comment by neraigo** [comment]
What's happening is the script thinks it is not on the home screen when it actually is. So it is trying to return to the home page by clicking the top left button to return to the home screen, but instead it is just removing the UI since it is already on home. 

The script checks a certain pixel to determine if it is on the home screen and for some reason on your setup the pixel check is returning an invalid color.

**Comment by Ryuuhou** [comment]
Please confirm if you see your mouse moving.

**Comment by aruruuruuu** [comment]
yeah the mouse is moving

**Comment by Ryuuhou** [comment]
Thank you, I've pretty much got an idea of what's going on.  I should be fixing it later tonight or tomorrow.  Unfortunately, WindowsXP does not support the background pixel check method so you will have to use the script with background mode disabled.  I will post the release as soon as I am done.

**Comment by Ryuuhou** [comment]
Go ahead and try the new update on the master branch.  Please let me know if it works so I can close the issue.
https://github.com/Ryuuhou/AHKanColle

**Comment by aruruuruuu** [comment]
well still the same result like b4  :(

**Comment by Ryuuhou** [comment]
Try the new commit on the master now, sorry this is taking so long, the code isn't working the way I wanted it to.

**Comment by aruruuruuu** [comment]
still the same like b4, but i think i know what the problem is, its clicking mainmenu button twice when its supposed to be only once. i testing it in the sortie menu screen. its clicking the main menu button, but ASAP i click the sortie menu then its clicking the main menu button again, then its clicking the resupply menu properly. its going smoothly until the exped was sent

**Comment by Ryuuhou** [comment]
https://github.com/Ryuuhou/AHKanColle/tree/Debug

One more test in hopes of figuring it out.  Do what you normally do, just type out the popup messages that come up.  Tell me at which point in the messages it hides the UI. For example, after the popup that says _____.  After it hides UI, do what you do to make the script continue until you see the popup "resupply"

**Comment by aruruuruuu** [comment]
1st initial: 0 -> do nothing
2nd not home: 0 -> clicking the home button
3rd resupply  -> clicking the home button again
then i manually revisiting homescreen by clicking sortie menu and get back to homescreen, no popup message, and the script continue smoothly

**Comment by aruruuruuu** [comment]
after it hides the UI, i tried click just to make the UI appear. and the script continue too

**Comment by Ryuuhou** [comment]
Sorry for the late reply, I could never really figure out why it was not working for you.  I have to guess it is windows XP.
