### ISSUE TITLE
AHKCSortie not selecting map

### ISSUE THREAD

**Issue by mintgreenrose** [Ryuuhou/AHKanColle#8]
I tried to run it for 3-2A powerleveling but it ends up getting stuck at the map selection screen, with the status of "waiting for compass". If I manually select the map and get to the compass it proceeds from there without a problem, until it loops back to the map selection. Not sure if it helps, but I'm on Win 7 using Chrome with KC3

**Comment by mintgreenrose** [comment]
Hi are you still working on this?

**Comment by Ryuuhou** [comment]
Sorry, I have been busy, I'll try to take a look at it tonight.

**Comment by Ryuuhou** [comment]
Do you see "World=3" and "Map=2" in your config.ini? Make sure you press the enter key after you type the 3 into the World box and the 2 in the Map box.  Make sure it says World Set at the bottom and Map Set at the bottom notification area.  I tested and it still works on my end.

I committed a new version of the sortie script which will notify you if the map/world have not been submitted.  https://github.com/Ryuuhou/AHKanColle/commit/93d596c4d7560976f6e65b00ca1995d8bb360afe

Please let me know if that solved your problem.

**Comment by mintgreenrose** [comment]
Ah I'm so boneheaded, why didn't I think of that all these days. It's working now... but if I may make a suggestion, if there could be an option to let the repair complete itself instead of using buckets. I'm just using Maruyu and repairs only take a few minutes, to use a bucket on a low level Maruyu is kind of overkill IMO :)

**Comment by Ryuuhou** [comment]
I'll think about the bucket saving, it is a lot of work to check for it so I will probably not have time to implement it.
