### ISSUE TITLE
Min and Max Wait for Sorties

### ISSUE THREAD

**Issue by mintgreenrose** [Ryuuhou/AHKanColle#9]
It would really be nice if there would also be a min and max wait for sorties as that would give it a sense of randomness and hopefully prevent the antibot measure from picking up on the on-the-dot initiation of sorties. Thanks! :)

**Comment by Ryuuhou** [comment]
Edit: It is now a part of master branch, give it a try.

**Comment by mintgreenrose** [comment]
Hey man just wanted to say it works like a charm. Thumbs up!

**Comment by Ryuuhou** [comment]
Glad it works for you.
